### ISSUE TITLE
getOrganization must throw if organization doesn't exist (like other functions do)

### ISSUE THREAD

**Issue by kvakes** [windingtree/org.id#4]
Perhaps I don't understand why looking up a non-existing org returns an org with "exist" flag set to false. There should be a more elegant way!

**Comment by kostysh** [comment]
Currently, there is not another correct way to indicate that organization does not exist.
It is not possible to use an exception throwing for functions what can be called by the external clients like `web3`. In case we will use exception throwing for such functions web3 application will not able to handle these errors because of only latest versions of `geth` Ethereum nodes (>= 1.9.13) supports reverts with reasons (or without it). There is the discussion (one of many): https://github.com/ethereum/web3.js/issues/3435

**Comment by kvakes** [comment]
Understood.
